### ISSUE TITLE
add possibility to balance the installation

### ISSUE THREAD

**Issue by freshworkx** [typo3-themes/Vagrant.Themes#12]
Add the possibility for user to balance the vagrant installation: Production or Development
Depending on the users choice, set:
- SetEnv TYPO3_CONTEXT in apache settings
- Development / Production settings under Configuration preset of install tool

**Comment by kaystrobach** [comment]
you can easily do that within the box by changing the .htaccess or via the installtool ... password joh316 ...

**Comment by freshworkx** [comment]
Your right, but a normal user can´t deal with htaccess or install tool. In my opinion it will be a good idea to set a appropriate variable in the vagrant file. Depending on this variable the system will be installed as a demo (with caching, fast) or as development (no caching, display errors on)

**Comment by kaystrobach** [comment]
changing the vagrant file is even worse, updating will then be totally crappy ... for the noobs we have demo.typo3-themes.org ... IMHO the vagrant box was built for developers and should never be used for production.

**Comment by freshworkx** [comment]
Agreed, normal users should use the online demo not the vagrant box
